# -*- coding: utf-8 -*-
"""quadratic equation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SJ0n0Mh6wBP7DNpXf_rvBxG0BjaFPOnf
"""

import numpy as np
a = 1
b = -3.29
c =  2.706
errors = (10**n for n in range(-12, 1))

for error in errors:
    now_c = c + error
    print(f'Error = {error}, roots = {np.roots([a, b, now_c])}')