# -*- coding: utf-8 -*-
"""cond.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19EXKt2o34TMTK8rp7Okt9ZaBuEGISvwX
"""

import numpy as np

A = np.array([[611, 196, -192, 407],
             [196, 899, 113, -192],
             [-192, 113, 899, 196],
             [407, -192, 196, 611]], dtype=float)

b = np.full((4,4), 0, dtype=float)
m = -np.Inf

for i in range(4):
  b[i, i] = 1
  x_i = np.linalg.solve(A, b[i])
  nor_i = np.linalg.norm(x_i)/np.linalg.norm(b[i])
  m = max(nor_i, m)

print(A)
norm_A = np.linalg.norm(A)
print(f'Экспериментальное число обусловенности матрицы:               {m*norm_A}')
print(f'Число обусловенности матрицы, полученное встроенной функцией: {np.linalg.cond(A)}')