# -*- coding: utf-8 -*-
"""gauss.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19EXKt2o34TMTK8rp7Okt9ZaBuEGISvwX
"""

import numpy as np
import math
import matplotlib.pyplot as plt

M = 5
n = 100
q = 1.001 - 2*M*10**(-3)
def search_b(x):
  b = np.zeros(n, dtype=float)
  for i in range(n):
    b[i] = abs(x-(n/10))*i*math.sin(x)
  return b

A = np.zeros((n,n), dtype=float)
for i in range(n):
  for j in range(n):
    if (i==j):
      A[i][j] = (q-1)**(i+j)
    else:
      A[i][j] = (q)**(i+j) + 0.1*(j-i)

def gauss_method(A, b):
    A = A.copy()
    b = b.copy()
    n = A.shape[0]
    b_tmp = []
    for i in range(n):
        max_val = abs(A[i, 0])
        max_i = i
        max_j = 0
        for j in range(i, n):
            for k in range(0, n):
                if abs(A[j, k])> max_val:
                    max_val = abs(A[j, k])
                    max_i = j
                    max_j = k
        b_tmp.append(max_j)
        if max_i!=i:
            tmp = A[i].copy()
            A[i] = A[max_i]
            A[max_i] = tmp
            tmp = b[i]
            b[i] = b[max_i]
            b[max_i] = tmp
        for k in range(i + 1, n):
            b[k] -= b[i] * A[k,max_j]/A[i,max_j]
            A[k] -= A[i] * A[k,max_j]/A[i,max_j]
    result = b.copy()
    for i in range(n-1, -1, -1):
        j = b_tmp[i]
        b[i]/=A[i,j]
        result[j] = b[i]
        for k in range(0, i):
            b[k] -= b[i] * A[k,j]
    return result

num = 50
point = np.linspace(-5.0, 5.0, num)
y = []
orig = []
for x in point:
  y.append(np.sum(gauss_method(A, search_b(x))))
  orig.append(np.sum(np.linalg.solve(A, search_b(x))))


plt.figure(figsize=(6, 5))
plt.plot(point, y)
plt.title("Реализованный метод Гаусса - метод прогонки")
plt.xlabel('x')
plt.ylabel('y(x)')
plt.show()
plt.savefig('graphic.png', dpi=300)

plt.figure(figsize=(6, 5))
plt.plot(point, orig)
plt.title("Встроенный метод Гаусса")
plt.xlabel('x')
plt.ylabel('orig(x)')
plt.show()
plt.savefig('orig_graphic.png', dpi=300)